=== jestark/LMSDataHarvester/src/main/resources/Profile.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
  -  Copyright (C) 2016 James E. Stark
  -
  -  This program is free software: you can redistribute it and/or modify
  -  it under the terms of the GNU General Public License as published by
  -  the Free Software Foundation, either version 3 of the License, or
  -  (at your option) any later version.
  -
  -  This program is distributed in the hope that it will be useful,
  -  but WITHOUT ANY WARRANTY; without even the implied warranty of
  -  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  -  GNU General Public License for more details.
  -
  -  You should have received a copy of the GNU General Public License
  -  along with this program.  If not, see <http://www.gnu.org/licenses/>.
  -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://icc.socs.uoguelph.ca/edm"
	targetNamespace="http://icc.socs.uoguelph.ca/edm" elementFormDefault="qualified">

	<xs:element name="profile" type="profile"/>

	<xs:complexType name="profile">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="mutable" type="xs:boolean" minOccurs="0"/>
			<xs:element name="parameter" type="parameter" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="element" type="element" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="parameter">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="name" type="xs:string" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="element">
		<xs:sequence>
			<xs:element name="generator" type="xs:string" minOccurs="0"/>
			<xs:element name="implementation" type="xs:string" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="class" type="xs:string"/>
	</xs:complexType>
</xs:schema>

=== jestark/LMSDataHarvester/conf/OutputProfile.xml
<?xml version="1.0" encoding="UTF-8"?>

<profile xmlns="http://icc.socs.uoguelph.ca/edm" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://icc.socs.uoguelph.ca/edm Profile.xsd">
	<name>coursedb</name>
	<mutable>true</mutable>

	<parameter name="javax.persistence.jdbc.url">jdbc:postgresql://DATABASE_HOST/DATABASE"</parameter>
	<parameter name="javax.persistence.jdbc.user">USERNAME</parameter>
	<parameter name="javax.persistence.jdbc.password">PASSWORD</parameter>

	<element class="ca.uoguelph.socs.icc.edm.domain.Element">
		<generator>ca.uoguelph.socs.icc.edm.domain.datastore.idgenerator.NullIdGenerator</generator>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.Action">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.ActionData</implementation>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.ActivityReference">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.ActivityReferenceData</implementation>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.ActivitySource">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.ActivitySourceData</implementation>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.ActivityType">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.ActivityTypeData</implementation>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.Course">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.CourseData</implementation>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.Enrolment">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.EnrolmentData</implementation>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.Grade">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.GradeData</implementation>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.LogEntry">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.LogData</implementation>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.Network">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.NetworkData</implementation>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.Role">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.RoleData</implementation>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.User">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.UserData</implementation>
	</element>
</profile>

=== jestark/LMSDataHarvester/conf/ScratchProfile.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  -  Copyright (C) 2016 James E. Stark
  -
  -  This program is free software: you can redistribute it and/or modify
  -  it under the terms of the GNU General Public License as published by
  -  the Free Software Foundation, either version 3 of the License, or
  -  (at your option) any later version.
  -
  -  This program is distributed in the hope that it will be useful,
  -  but WITHOUT ANY WARRANTY; without even the implied warranty of
  -  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  -  GNU General Public License for more details.
  -
  -  You should have received a copy of the GNU General Public License
  -  along with this program.  If not, see <http://www.gnu.org/licenses/>.
  -->

<!-- Sample Profile for the scratch data-store -->

<profile xmlns="http://icc.socs.uoguelph.ca/edm" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://icc.socs.uoguelph.ca/edm Profile.xsd">
	<name>mem</name>
	<mutable>true</mutable>

	<!--
	  -  Default Element and IdGenerator implementations.  These should not need
	  -  to be changed.
	  -->

	<element class="ca.uoguelph.socs.icc.edm.domain.Element">
		<generator>ca.uoguelph.socs.icc.edm.domain.datastore.idgenerator.SequentialIdGenerator</generator>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.Action">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.ActionData</implementation>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.ActivityReference">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.ActivityReferenceData</implementation>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.ActivitySource">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.ActivitySourceData</implementation>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.ActivityType">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.ActivityTypeData</implementation>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.Course">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.CourseData</implementation>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.Enrolment">
		<generator>ca.uoguelph.socs.icc.edm.domain.datastore.idgenerator.RandomIdGenerator</generator>
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.EnrolmentData</implementation>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.Grade">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.GradeData</implementation>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.LogEntry">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.LogData</implementation>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.Network">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.NetworkData</implementation>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.Role">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.RoleData</implementation>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.User">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.UserData</implementation>
	</element>
</profile>

=== jestark/LMSDataHarvester/conf/InputProfile.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  -  Copyright (C) 2016 James E. Stark
  -
  -  This program is free software: you can redistribute it and/or modify
  -  it under the terms of the GNU General Public License as published by
  -  the Free Software Foundation, either version 3 of the License, or
  -  (at your option) any later version.
  -
  -  This program is distributed in the hope that it will be useful,
  -  but WITHOUT ANY WARRANTY; without even the implied warranty of
  -  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  -  GNU General Public License for more details.
  -
  -  You should have received a copy of the GNU General Public License
  -  along with this program.  If not, see <http://www.gnu.org/licenses/>.
  -->

<!-- Sample Profile for the source database -->

<profile xmlns="http://icc.socs.uoguelph.ca/edm" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://icc.socs.uoguelph.ca/edm Profile.xsd">
	<name>moodledb</name>

	<!--
	  -  JPA parameters.  These can can be any valid parameters for the JPA
	  -  implementation.  They will be passed directly to the JPA
	  -  EntityManagerFactory.  In most cases these should be the database URL,
	  -  username, and password.  The URL must be a valid JDBC URL.  The URL
	  -  may specify an SSL connection if the database has a valid certificate.
	  -
	  -  It is strongly recommended that the source datastore be a copy of the
	  -  Moodle database, and not a live version.  Furthermore, the user
	  -  specified here should have read-only access.
	  -->

	<parameter name="javax.persistence.jdbc.url">jdbc:postgresql://DATABASE_HOST/DATABASE</parameter>
	<parameter name="javax.persistence.jdbc.user">USERNAME</parameter>
	<parameter name="javax.persistence.jdbc.password">PASSWORD</parameter>

	<!--
	  -  Default Element and IdGenerator implementations.  These should not need
	  -  to be changed.
	  -->

	<element class="ca.uoguelph.socs.icc.edm.domain.Element">
		<generator>ca.uoguelph.socs.icc.edm.domain.datastore.idgenerator.NullIdGenerator</generator>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.ActivityReference">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.MoodleActivityReference</implementation>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.ActivityType">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.MoodleActivityType</implementation>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.Course">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.CourseData</implementation>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.Enrolment">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.EnrolmentData</implementation>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.LogEntry">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.MoodleLogData</implementation>
	</element>
	<element class="ca.uoguelph.socs.icc.edm.domain.User">
		<implementation>ca.uoguelph.socs.icc.edm.domain.element.UserData</implementation>
	</element>
</profile>
